from importlib import util
import pywikibot

site = pywikibot.Site("en", "wowpedia")

def load_file_as_module(name, location):
	spec = util.spec_from_file_location(name, location)
	module = util.module_from_spec(spec)
	spec.loader.exec_module(module)
	return module

# generated by Scribunto/API_info/systems/category_pages.lua
mod = load_file_as_module("mymodule", "wowpedia/category/namespace.py")

fs = """[[Category:API namespaces|{!s}]]
===External links===
{{{{#invoke:API namespaces|main|filename={!s}|system={!s}}}}}"""

for v in mod.namespaces:
	fileName, systemName, sytemNamespace = v[0], v[1], v[2]
	if sytemNamespace:
		page = pywikibot.Page(site, "Category:API_namespaces/"+sytemNamespace)
		if not page.exists:
			page.text = fs.format(sytemNamespace.replace("C_", ""), fileName, systemName)
			page.save(summary="12.0.0 (64741)")

print("done")
