local loader = require("wowdoc.loader")
local cfg = require("wowdoc.loader.config")
loader:LoadDocumentation(cfg.TACT_PRODUCT)
require("warcraftwiki")
--require("warcraftwiki.tests")
local Exporter = require("Documenter.Exporter")
Exporter:ExportSystems(cfg.path.WARCRAFTWIKI)
